enum ContactType {
  PRESS = "PRESS",
  SPEAKER = "SPEAKER",
  TALK = "TALK",
  LIGHTNING_TALK = "LIGHTNING_TALK",
  KEYNOTE = "KEYNOTE",
  WORKSHOP = "WORKSHOP",
  WORKSHOP_HOST = "WORKSHOP_HOST",
  ORGANIZER = "ORGANIZER",
  SPONSOR = "SPONSOR",
  GOLD_SPONSOR = "GOLD_SPONSOR",
  SILVER_SPONSOR = "SILVER_SPONSOR",
  BRONZE_SPONSOR = "BRONZE_SPONSOR",
  PARTNER = "PARTNER",
  ATTENDEE = "ATTENDEE",
}

export default ContactType;
